# Generated by Django 3.1.3 on 2021-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NamuKiwi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagedata',
            name='id',
        ),
        migrations.AddField(
            model_name='pagedata',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagedata',
            name='subject',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
